version: '3.7'

services:
  cat-demo:
    build: .
    ports: [8080:8080, 8181:8181]
    container_name: cat-demo
    networks:
      monitoring:
        aliases:
          - cat-demo
  grafana:
    image: grafana/grafana:7.1.0
    ports: [3000:3000]
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus:v2.19.2
    ports: [9090:9090]
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

networks:
  monitoring:
    driver: bridge