# Application info
info.app.version: 1.0.0

# Configure endpoints
management:
  server.port: 8181
  endpoint:
    shutdown.enabled: true
    health.show-components: always
    health.show-details: always
  endpoints.web:
    base-path: "/monitoring"
    path-mapping.shutdown: "/kill"
    exposure.include: "shutdown, info, health, cats, prometheus, metrics, logfile"

# Database
spring.h2.console.enabled: true
spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource:
  url: "jdbc:h2:./db/cats"
  driverClassName: org.h2.Driver
  username: sa
  password:
